# --------------------------------------------------------------------------- #
# Project Info
#   Defaults shown. Learn more about these options by running
#   `fontcustom help` or visiting <http://fontcustom.com>.
# --------------------------------------------------------------------------- #

font_name: icons
css_selector: .icon-{{glyph}}
preprocessor_path: ""
autowidth: false
no_hash: false
force: false
debug: false
quiet: false


# --------------------------------------------------------------------------- #
# Input Paths
# --------------------------------------------------------------------------- #

input:
  vectors: lib/assets/icons/svg
  templates: lib/assets/icons/templates


# --------------------------------------------------------------------------- #
# Output Paths
# --------------------------------------------------------------------------- #

output:
  fonts: app/assets/fonts                              # required
  css: app/assets/stylesheets


# --------------------------------------------------------------------------- #
# Templates
#   Included in Font Custom: preview, css, scss, scss-rails
#   Custom templates should be saved in the INPUT[:templates] directory and
#   referenced by their baserame.
# --------------------------------------------------------------------------- #

templates:
 - _icon_font.scss
